Blog/config/routes.rb
Rails.application.routes.draw do
  # get 'likes/create'
  # get 'likes/destroy'
  # get 'likes/like_params'

  resources :likes, only: [:create, :destroy]
  
  resources :comments
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }
  get 'home/about'
  root 'posts#index'

  get 'posts/mypost', to: 'posts#mypost'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  scope "(:locale)", locale: /en|ru/ do
    get '/about', to: 'home#about', as: :about
  end
end

Blog/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :images, presence: true

  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many_attached :images
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
  end

  def new
    @post = Post.new
  end

  def create
    UserMailer.alert_admin.deliver
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  def mypost
    @posts = Post.all
  end

  private
    def post_params
      params.require(:post).permit(:title, :description,:user_id,:is_published,images:[])
    end

end

Blog/app/views/posts/_form.html.erb
<div class="container p-3" style = 'margin-bottom: 100px'>
    <%= form_with model: post do |form| %>
    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div class = "form-control m-2" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; width: 450px; background-color: #edf4f4;font-size:24px">
                <%= form.label :title %><br>
                <%= form.text_field :title %>
                <div class = 'text-danger'><%= @post.errors.full_messages_for(:title).first %></div>
        </div>
        </div>
    </div>

    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div class = "form-control m-2 mb-0" style="border-color: #adb5bd; border-radius: 2px;width: 450px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                <%= form.label :description %><br>
                <%= form.text_field :description %><br>
                <div class = 'text-danger'><%= @post.errors.full_messages_for(:description).first %></div>
              </div>
        </div>
    </div>

    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div class = "form-control m-2 mb-0" style="border-color: #adb5bd; border-radius: 2px;width: 450px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                <%= form.file_field :images, multiple: true%><br>
                <div class = 'text-danger'><%= @post.errors.full_messages_for(:images).first %></div>
              </div>
        </div>
    </div>

    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div>
                <%= form.text_field :user_id, type: "hidden", value: current_user.id %><br>
              </div>
        </div>
    </div>

    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div class = " m-2 mt-0" >
                <%= form.submit class: 'btn btn-primary col-12 form-conntrol', style: 'font-size:24px; width: 450px;' %>
              </div>
        </div>
    </div>
    <%end%>
</div>

Blog/app/views/posts/_permission.html.erb
 <div class="container" style = 'margin-bottom:100px' >
    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;" >
            <% if current_user.role == 'admin' or current_user.role == 'reviewer'%>
  <%= form_with model: @post do |form| %>
  
  <div class = "form-control m-2 p-3" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px; ">
     <%= form.label :is_published,:class => "label" %><br>
  <%= form.radio_button :is_published, true %> Publish<br />
    <%= form.radio_button :is_published, false %> Unpublish<br />    
  </div>



  <div class = "form-control m-2 mt-0 p-3" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
    <%= form.submit class: 'btn btn-primary col-12 form-conntrol', style: 'font-size:24px' %>
  
<% end %>
<% end %>

        </div>
    </div>
   </div>

Blog/app/views/posts/_post.html.erb
<div class="container w-50">
    
    <div class="row">
        <div class="col bg-primary text-light mb-2" style="display: flex; justify-content: center; align-items: center;">
            <h1>Posts</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                <div class="card-body" style = "display: flex; justify-content: center; align-items: center;"><% @posts.each do |post| %>
                    <% if post.is_published == true %>
                     
                       <li> <%= link_to post.title, post %> </li>
                                          
                    <% end %>
                    <% end %>
                 </div>
            </div>
        </div>
    </div>

</div>

Blog/app/views/posts/_publishandunpublishpost.html.erb
<div class="container" style = 'margin-bottom: 100px' >
    <div class="row">
        <div class="col-6 ">
            <div class="row">
                <div class="col bg-primary text-white mb-3 me-1"><h2>Published Posts</h2></div>
            </div>

            <div class="row">
                
                <div class="col">
                    <div class="card" style="width:100%; border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                        
                            <div class="card-body"><% @posts.each do |post| %>
                                <% if post.is_published == true %>
                                  
                                    <li><%= link_to post.title, post %></li>
                                    <% post.images do |image|%>  
                                    <%= image_tag(image)%>    
                                    <% end %> 
                                <% end %>
                                <% end %>
                              </div> 
                            </div>
                        </div>
                      
                </div>

            </div>
        

        
        
        
        <div class="col-6 ">
            <div class="row">
                <div class="col bg-primary text-white mb-3 ms-1"><h2>Unpublished Posts</h2></div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="card" style="width:100%; border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                        <div class="card-body">
                        <% @posts.each do |post| %>
                            <% if post.is_published == false %>
                              
                                <li><%= link_to post.title, post %></li>
                                <% post.images do |image|%>  
                                    <%= image_tag(image)%>    
                                    <% end %> 
                            <% end %>
                            <% end %>
                          
                          
                          </div> 
                      </div>
                </div>

                
            </div>
        </div>


    </div>
   </div>

Blog/app/views/posts/edit.html.erb
<h1 style="display: flex; justify-content: center; align-items: center;">Edit Post</h1>



<div class="container">
    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;">
          <%= form_with model: @post do |form| %>
  <% if current_user.id.to_i == @post.user_id.to_i %>
  <div class = "form-control m-2 p-3" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px"> 
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class = "form-control m-2 p-3" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
    <%= form.label :description %><br>
    <%= form.text_field :description %><br>
    <% @post.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  

  <div>
    <%= form.text_field :user_id, type: "hidden", value: current_user.id %><br>
  </div>


 

  <div class = "form-control m-2 mt-0 p-3" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
    <%= form.submit class: 'btn btn-primary col-12 form-conntrol', style: 'font-size:24px' %>
  </div>
<% end %>
<% end %>
        </div>
    </div>
   </div>

   
<%= render 'permission'%>








   



 

Blog/app/views/posts/index.html.erb
<% if current_user.role == 'writer' %>
   <%= render "post" %>
    <% end %>

 <% if current_user.role == 'admin' or current_user.role == 'reviewer'%>
   <%= render "publishandunpublishpost" %>
   <% end %>


   

Blog/app/views/posts/mypost.html.erb
<div class="container" >
        
        <div class="row mt-3">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
                <div class="card shadow-lg" style="width:600px; border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;font-size:24px">
                <div class="card-header bg-primary text-white"><h2>My Posts</h2></div>
                    
                    <div class="card-body">
                        <ul>
                            <% @posts.each do |post| %>
                          <% if current_user.id.to_i == post.user_id.to_i %>
                           
                           <li>
                                <%= link_to post.title, post %>
                              </li>
                          
                          <% end %>
                          <% end %>
                          </ul>
                    </div>
                  </div>
            </div>
        </div>
    </div>

Blog/app/views/posts/new.html.erb
<h1 class = "mt-5" style="display: flex; justify-content: center; align-items: center;">New Post</h1>

<%= render "form", post: @post %>

Blog/app/views/posts/show.html.erb
<div class="container w-50">
    <div class="row">
        <div class="col" style="display: flex; justify-content: center; align-items: center;margin-bottom: 100px;">
            <div class="card shadow-lg" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;">
                <div class="card-header bg-primary text-white" style="display: flex; justify-content: center; align-items: center;"><h1><%= @post.title %></h1></div>
                <div class="card-body" >
                    <div style="display: flex; justify-content: center; align-items: center;"><p> <% @post.images.each do |image| %>
                        <%= image_tag(image, style: 'height: 100%; width: 100%; object-fit: contain;', class: 'pt-3 ') %>
                        <% end %></p> </div>
                        <div class = 'mb-2' style="display: flex; justify-content: center; align-items: center; font-size:26px"></b><br><%= @post.description %></p></div>
                        <div style="display: flex; justify-content: center; align-items: center;">
                        <% if user_signed_in? and current_user.role == 'writer' and current_user.id.to_i != @post.user_id.to_i %>
                        <% like = current_user.likes.find_by(post: @post) %>
                        <% if like.nil? %>
                          <%= button_to "like", likes_path, params: { like: { post_id: @post.id }}, method: :post , class: 'btn btn-outline-danger me-2'%>
                        <% else %>
                          <%= button_to "Unlike", like_path(like), method: :delete, class: 'btn btn-outline-success me-2' %>
                        <% end %>
                      <% end %>
                       <b class = 'text-danger'><%= @post.likes.count %> Likes </b>
                       </div>
                </div>
                <div class="card-footer">
                <% if current_user.role == 'writer' and current_user.id.to_i != @post.user_id.to_i%>
                <%= render 'comments/form',comment: @comment%></div>
                <% end %>
                <div style="display: flex; justify-content: center; align-items: center; font-size: 24px">
                <ul>
                <h3> Comments </h3>
                <%a = @post.comments.count%>
                <% @post.comments.each_with_index do|comment,index| %>
                        <% if index < a %>
                        <li><%=  comment.text %> <% if current_user.role == 'admin' or current_user.id.to_i == @post.user_id.to_i%>
<%= button_to "Delete comment", comment, method: :delete, class: 'btn btn-outline-danger' %>
<% end %> </li>
                         
                        <% end %>
                  <% end %>
                  </ul>
                </div>
                <hr>
                <div style="display: flex; justify-content: center; align-items: center; font-size: 24px"> <% if current_user.id.to_i == @post.user_id.to_i or current_user.role == 'admin' or current_user.role == 'reviewer' %>
                
        <ul>
  <li><%= link_to "Edit", edit_post_path %></li>
  <% if current_user.role == 'admin' or current_user.id.to_i == @post.user_id.to_i%>
  <li><%= link_to "Destroy", post_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
                  <% end %>
</ul>
  <% end %> </div>
              </div>              
        </div>
    </div>
   </div>