Vlog/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
    member do
      patch :upvote
      patch :downvote
    end
  end
  get 'post/myposts',to: 'posts#myposts'
  devise_scope :user do
  get "/users/sign_out", to:'devise/sessions#destroy'
  end
  resources :users, only: [:show]

  resources :comments do
    member do
      patch :upvote
      patch :downvote
    end
  end
  
end

Vlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Vlog/app/models/comment.rb
class Comment < ApplicationRecord
    # belongs_to :user
    belongs_to :post
    acts_as_votable
end

Vlog/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :images, presence: true
  has_many_attached :images
  has_many :comments
  acts_as_votable
end

Vlog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :email ,presence: true
         validate :email_format

         validate :password_lower_case
         validate :password_uppercase
         validate :password_special_char
         validate :password_contains_number
       
         def password_uppercase
           return if !!password.match(/\p{Upper}/)
           errors.add :password, ' must contain at least 1 uppercase '
         end
       
         def password_lower_case
           return if !!password.match(/\p{Lower}/)
           errors.add :password, ' must contain at least 1 lowercase '
         end
       
         def password_special_char
           special = "?<>',?[]}{=-)(*@&^%$#`~{}!"
           regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
           return if password =~ regex
           errors.add :password, ' must contain special character'
         end
       
         def password_contains_number
           return if password.count("0-9") > 0
           errors.add :password, ' must contain at least one number'
         end
         
         def email_format
          test_string = $1 if email =~ /\<([^\>]+)\>/
          test_string = email.split(' ').last unless test_string
          return if test_string =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
          errors.add(:email, "not a valid email")
        end        
  
  has_many :posts
  acts_as_voter
end

Vlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Vlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def upvote
    @comment = Comment.find(params[:id])
    if current_user.voted_up_on? @comment
    @comment.unvote_by current_user
    else
    @comment.upvote_by current_user
    end
    redirect_to @comment.post	
  end


  def downvote
    @comment = Comment.find(params[:id])
    if current_user.voted_down_on? @comment
    @comment.unvote_by current_user
    else
    @comment.downvote_by current_user
    end
    redirect_to @comment.post	
  end

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
    posts_path
    format.html { redirect_to @comment.post}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:text, :user_email, :post_id)
    end
end

Vlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def upvote
    @post = Post.find(params[:id])
    if current_user.voted_up_on? @post
    @post.unvote_by current_user
    else
    @post.upvote_by current_user
    end
    redirect_to post_path	
  end

  def downvote
    @post = Post.find(params[:id])
    if current_user.voted_down_on? @post
    @post.unvote_by current_user
    else
    @post.downvote_by current_user
    end
    redirect_to post_path	
  end


    def index
        @posts = Post.all
    end

    def myposts
      @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
        @comment = @post.comments.build
    end

    def new
        @post = Post.new
      end
    
      def create
        @post = Post.new(post_params)
    
        if @post.save
          redirect_to @post
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
        @post = Post.find(params[:id])
      end
    
      def update
        @post = Post.find(params[:id])
    
        if @post.update(post_params)
          redirect_to @post
        else
          render :edit, status: :unprocessable_entity
        end
      end
    
      def destroy
        @post = Post.find(params[:id])
        @post.destroy
    
        redirect_to root_path, status: :see_other
      end

      

      private
        def post_params
          params.require(:post).permit(:title, :user_id, :description, images: [])
        end
end

Vlog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

Vlog/app/helpers/application_helper.rb
module ApplicationHelper
end

Vlog/app/helpers/comments_helper.rb
module CommentsHelper
end

Vlog/app/helpers/posts_helper.rb
module PostsHelper
end

Vlog/app/helpers/users_helper.rb
module UsersHelper
end

Vlog/app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

Vlog/app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-control mb-2'>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    
    <%= form.text_field :user_email, type: 'hidden',value:current_user.email %>
  </div>

  <div>    
    <%= form.text_field :post_id, type: 'hidden' %>
  </div>

  <div>
    <%= form.submit class: 'col-12 btn btn-primary' %>
  </div>
<% end %>

Vlog/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

Vlog/app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

Vlog/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

Vlog/app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

Vlog/app/views/layouts/_footer.html.erb
<div class="container-fluid bg-primary text-light fixed-bottom p-2 mt-5">
      <div class="row">
        <div class="col-md d-flex justify-content-center align-items-center">
          <i class="fa-regular fa-2x fa-copyright mb-1 me-1" style="color: white"></i>
          <h2><i>Vlog</i></h2>
        </div>
      </div>
    </div>

Vlog/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg shadow-lg ">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out',destroy_user_session_path, class: 'nav-link active'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Upload Post',new_post_path, class: 'nav-link active'%>
        </li>
        <li class="nav-item">
          <%= link_to 'My Posts', post_myposts_path, class: 'nav-link active'%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

Vlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
        .custom {
            background: url("https://images.unsplash.com/photo-1628838481489-d9d5b860566e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ0fHxiYW5uZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60") no-repeat center/cover;
            background-position: center;
            height: auto;
        }
    </style>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

Vlog/app/views/posts/_banner.html.erb
    <div class="container-fluid d-flex justify-content-center align-items-center p-5 custom">
        <div class="row justify-content-center align-items-center w-50 " style="margin: 80px 0px;">
            <div class="col-lg">
                <div class="row">
                    <div class="col-md">
                        <p class="text-light" style="font-size: 30px">
                            Something short and leading about the collection below—its
                            contents, the creator, etc. Make it short and sweet, but not too
                            short so folks don’t simply skip over it entirely.
                        </p>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

Vlog/app/views/posts/_form.html.erb
<div class="container" style='margin-bottom:100px'>
        <%= form_with model: post do |form| %>
        <div class="row">
            <div class="col"style="display: flex; justify-content: center; align-items: center;">
                <div>
                    <%= form.label :title %><br>
                    <%= form.text_field :title, class:'form-control',style:'width:335px' %>
                    <div class = 'text-danger'><%= post.errors.full_messages_for(:title).first %></div>
                  </div>
            </div>
        </div>

        <div class="row">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
                <div>
                    <%= form.label :description %><br>
                    <%= form.text_field :description, class:'form-control',style:'width:335px' %><br>
                    <div class = 'text-danger'><%= @post.errors.full_messages_for(:description).first %></div>
                  </div>
            </div>
        </div>

      <div class="row">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
            <div>
                <%= form.label :images %><br>
                <%= form.file_field :images, multiple: true ,class: 'form-control'%><br>
                <div class = 'text-danger'><%= post.errors.full_messages_for(:images).first %>
                </div>
            </div>
      </div>
      </div>
                
        <%= form.text_field :user_id, value: current_user.id, type: 'hidden' %><br>     

        <div class="row">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
                <div>
                    <%= form.submit class: 'col-12 btn btn-primary',style:'width:335px' %>
                  </div>
            </div>
        </div>
        <% end %>
    </div>

Vlog/app/views/posts/edit.html.erb
<%= render 'banner'%>
<div class="container mt-5">
        <div class="row">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
                <h1> Edit Post </h1>
            </div>
        </div>
    </div>
<%= render "form", post: @post %>

Vlog/app/views/posts/index.html.erb
<%= render 'banner'%>
<div class="container mt-5" style='margin-bottom:100px'>
        <div class="row justify-content-center align-items-center">
            <% @posts.each do |post| %>
            <div class="col-md-6 col-lg-4" >
                <div class="card mb-5" style="border-width: 1px; background-color: #edf4f4;">
                    <div class="card-header" style='height:250px;display: flex; justify-content: center; align-items: center;'>
                        <% post.images.each do |image| %>
                        <%= image_tag(image, style: ' width:100%; height:100%',class: 'shadow card-top card-bg') %>
                        <% end %> 
                    </div>
                    <div class="card-body" style='display: flex; justify-content: center; align-items: center;'>
                        <h4><%= link_to post.title, post %></h4>
                    </div>
                    <div class="card-footer" style='display:flex; justify-content: center; align-items: center;'><b> <%= post.description%></b> </div>
                  </div>                
            </div>
            <% end %>
        </div>
    </div>


    

Vlog/app/views/posts/myposts.html.erb
<%= render 'banner'%>
<div class="container mt-5" style='margin-bottom:100px'>
        <div class="row justify-content-center align-items-center">
        <% @posts.each do |post| %>
          <%if current_user.id.to_i == post.user_id.to_i %>
            <div class="col-md-6 col-lg-4" >
                <div class="card mb-5" style="border-width: 1px; background-color: #edf4f4;">
                    <div class="card-header" style='height:250px;display: flex; justify-content: center; align-items: center;'>
                        <% post.images.each do |image| %>
                        <%= image_tag(image, style: ' width:100%; height:100%',class: 'shadow card-top card-bg') %>
                        <% end %> 
                    </div>
                    <div class="card-body" style='display: flex; justify-content: center; align-items: center;'>
                        <h4><%= link_to post.title, post %></h4>
                    </div>
                    <div class="card-footer" style='display:flex; justify-content: center; align-items: center;'><b> <%= post.description%></b> </div>
                  </div>                
            </div>
            <% end %>
        <% end %>
        </div>
    </div>


    

Vlog/app/views/posts/new.html.erb
<%= render 'banner'%>
<div class="container mt-5">
        <div class="row">
            <div class="col" style="display: flex; justify-content: center; align-items: center;">
                <h1> New Post </h1>
            </div>
        </div>
    </div>
<%= render "form", post: @post %>

Vlog/app/views/posts/show.html.erb
<div class="container  mt-5" style= 'margin-bottom:100px'>
        <div class="row justify-content-center align-items-center">
            <div class="col-md-8 col-lg-6">
                <div class="card" style="border-color: #adb5bd; border-radius: 2px; border-width: 1px; background-color: #edf4f4;">
                    <div class="card-header bg-primary text-light">
                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <h1><%= @post.title%></h1>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <% @post.images.each do |image| %> 
                                    <%= image_tag(image, style: ' width:75%; height:75%',class: 'shadow card-top card-bg') %>
                                <% end %>      
                            </div>
                        </div>

                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <h3><%= @post.description %></h3>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <% if current_user.id.to_i != @post.user_id.to_i %>
                                <%= button_to "",upvote_post_path(@post), style: 'color:red',class: 'btn fa-regular fa-heart fa-2x',method: :patch %><br>
                                <% end %>

                                <div class = "ms-1">
                                    <h4>Likes <%= @post.votes_for.up.size%></h4>
                                </div>
                                
                            </div>

                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <% if current_user.id.to_i != @post.user_id.to_i %>
                                <%= button_to "",downvote_post_path(@post), class: 'btn fa-solid fa-2x fa-heart-crack',method: :patch %><br>
                                <% end %>
                                <div class = "ms-1">
                                    <h4>Dislikes <%= @post.votes_for.down.size%></h4>
                                </div>
                            </div>
                        </div>
                        <%if current_user.id.to_i != @post.user_id.to_i%>
                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <%= render "comments/form", comment: @comment%>
                            </div>
                        </div>
                        <%end%>

                        <div class="row" >
                            <%a = @post.comments.count%>
                            <%@post.comments.each_with_index do|comment,index| %>
                            <% if index < a %>
                            
                            <div class="row">
                                <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <b>Commenter: </b> <%= comment.user_email %>    
                                </div>
                            </div>

                            <div class="row">
                                <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                    
                                    <%= comment.votes_for.up.size%><%= button_to  "",upvote_comment_path(comment),class: 'btn me-2 fa-sharp fa-regular fa-thumbs-up fa-2x',style: 'color:blue',method: :patch %><%= comment.text %>  <%= button_to "",downvote_comment_path(comment),class: 'btn  ms-2 fa-sharp fa-regular fa-thumbs-down fa-2x',method: :patch %><div class = "ms-1"><%= comment.votes_for.down.size%></div>
                                </div>
                            </div>

                            <%if current_user.id.to_i == @post.user_id.to_i%>
                            <div class="row">
                                <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                    <%= button_to "Delete comment", comment, method: :delete, class: 'btn btn-outline-danger' %>
                                </div>
                            </div>
                            <%end%>
                            <%end%>
                            <%end%>
                        </div>

                    </div>
                    <% if current_user.id.to_i == @post.user_id.to_i%>
                    <div class="card-footer">
                    
                        <div class="row">
                            <div class="col" style="display:flex;justify-content: center; align-items: center;">
                                <ul><li><%= link_to "Edit", edit_post_path(@post) %></li>
                                <li><%= link_to "Destroy", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li></ul>
                            </div>
                        </div>
                        
                    </div>
                    <% end %>
                  </div>
            </div>
        </div>
    </div>

Vlog/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.email %>