Blog/config/routes.rb
Rails.application.routes.draw do
  # get 'likes/create'
  # get 'likes/destroy'
  # get 'likes/like_params'

  resources :likes, only: [:create, :destroy]
  
  resources :comments
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }
  get 'home/about'
  root 'posts#index'

  get 'posts/mypost', to: 'posts#mypost'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  scope "(:locale)", locale: /en|ru/ do
    get '/about', to: 'home#about', as: :about
  end
end

Blog/app/views/layouts/_footer.html.erb
<div class="container-fluid bg-primary text-light fixed-bottom p-2 mt-5">
      <div class="row">
        <div class="col-md d-flex justify-content-center align-items-center">
          <i class="fa-regular fa-1.5x fa-copyright mb-1 me-1" style="color: white"></i>
          <h4><i>Role Management</i></h4>
        </div>
      </div>
    </div>

Blog/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow-lg mb-5" style = 'font-size:25px'>
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       

        <li class="nav-item">
          <%= link_to 'About Page', home_about_path, class: 'nav-link active'%>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link active'%>
        </li>

        
        <% if current_user.role == 'writer'%>
        <li class="nav-item">
          <%= link_to 'My Posts', posts_mypost_path, class: 'nav-link active'%>
        </li>

        <li class="nav-item">
          <%= link_to 'Upload Post', new_post_path, class: 'nav-link active'%>
        </li>

        <% end %>

        
        <li class="nav-item">
          <%= link_to 'My Profile', current_user, class: 'nav-link active'%>
        </li>
        

        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path	, class: 'nav-link active'%>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        
      </form>
    </div>
  </div>
</nav>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    />

  </head>

  <body>

  <%= render 'layouts/navbar'%>
    <%= yield %>

 <%= render 'layouts/footer'%>
  </body>
</html>